# Add resource limits
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dspace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dspace
        app: dspace
    spec:
      containers:
      - name: dspace
        image: 270536341817.dkr.ecr.us-east-1.amazonaws.com/dspace:latest
        env:
          # These are not dspace values, but are used to bootstrap the container.
          - name: POSTGRES_HOST
            value: postgres
          - name: PGPASSWORD
            value: dspace
          - name: POSTGRES_PORT
            value: "5432"
          # DSpace configs
          - name: DSPACE_DIR
            value: /dspace
          - name: DSPACE_HOSTNAME
            value: http://a21e9c30788c511e7b25e0648761fa5c-350127752.eu-west-1.elb.amazonaws.com
          - name: DSPACE_BASEURL
            value: "http://${hostname}:8080"
          - name: DSPACE_URL
            value: "${baseUrl}"
          # DB configs
          - name: DB_URL
            value: jdbc:postgresql://postgres:5432/dspace
          - name: DB_USERNAME
            value: dspace
          - name: DB_PASSWORD
            value: dspace
          - name: DB_DRIVER
            value: org.postgresql.Driver
          - name: DB_SCHEMA
            value: ""
        ports:
          - name: dspace
            containerPort: 8080
            protocol: TCP
