# Add resource limits
# Create secrets
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: dspace
spec:
  serviceName: dspace
  replicas: 1
  template:
    metadata:
      labels:
        app: dspace
    spec:
      containers:
      - name: dspace
        image: 270536341817.dkr.ecr.us-east-1.amazonaws.com/dspace:latest
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: $NAME
                key: password
          # These are not dspace values, but are used to bootstrap the container.
          - name: POSTGRES_HOST
            value: postgres
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: $NAME
                key: password
          - name: POSTGRES_PORT
            value: "5432"
          # DSpace configs
          - name: DSPACE_DIR
            value: /dspace
          - name: DSPACE_HOSTNAME
            value: http://a21e9c30788c511e7b25e0648761fa5c-350127752.eu-west-1.elb.amazonaws.com
          - name: DSPACE_BASEURL
            value: ${dspace.hostname}
          # DB configs
          - name: DB_URL
            value: jdbc:postgresql://postgres:5432/dspace
          - name: DB_USERNAME
            value: dspace
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: $NAME
                key: password
          # Mail configs
          - name: MAIL_SERVER
            value: email-smtp.us-east-1.amazonaws.com
          - name: MAIL_SERVER_PORT
            value: '25'
          # S3 configs
          - name: NAME
            value: $NAME
          - name: S3_BUCKET_SIZE
            value: 5TB
        ports:
          - name: dspace
            containerPort: 80
            protocol: TCP
        volumeMounts:
          - name: aws-config
            mountPath: /config
      initContainers:
      - name: aws-bootstrap
        image: jkosgei/aws-bootstrap
        env:
          # AWS Credentials
          - name: NAME
            value: $NAME
          - name: REGION
            value: eu-west-1
          - name: EMAIL
            value: webmaster@knowledgearc.com
          - name: AWS_ACCESS_KEY_ID
            value: 
          - name: AWS_SECRET_ACCESS_KEY
            value: 
        volumeMounts:
          - name: aws-config
            mountPath: /config
  volumeClaimTemplates:
  - metadata:
      name: aws-config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi