apiVersion: v1
kind: Service
metadata:
  name: dspace
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: dspace
    port: 8080
    protocol: TCP
  selector:
    app: dspace
