apiVersion: v1
kind: Service
metadata:
  name: dspace
  namespace: $NAME
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: dspace
    port: 80
    protocol: TCP
  selector:
    app: dspace
